actor/urls.py
from django.urls import path
from actor.views import actors



urlpatterns = [
    path('<slug:actor_slug>',actors,name="actors"),
]

authy/urls.py
from django.urls import path
from movie.views import index,paginate,movieDetails,genres
from authy.views import Signup , PasswordChange  , EditProfile
from django.contrib.auth.views import (PasswordChangeView,LoginView ,
LogoutView ,PasswordChangeDoneView ,PasswordResetView
 , PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView)

app_name = "authy"
urlpatterns = [
    path('edit/', EditProfile, name='edit-profile'),
    path('signup/',Signup,name='signup'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),

    path('password_change/',PasswordChange.as_view(),name='password_change'),
    path('password_change/done/',PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    
]

imdb_clone_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static
from authy.views import UserProfile
urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('movie.urls')),
    path('actors/', include('actor.urls')),
    path('account/', include('authy.urls')),
    path('<username>/',UserProfile,name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

actor/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class Actor(models.Model):
    name= models.CharField(max_length=70,unique=True)
    picture = models.ImageField(blank=True)
    slug = models.SlugField(null=True,unique=True)
    movies = models.ManyToManyField('movie.Movie')
    
    def get_absolute_url(self):
        return reverse("actors",args=[self.slug])

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args,**kwargs)    

actor/views.py
from django.shortcuts import render,get_object_or_404
from actor.models import Actor
from django.http import HttpResponse , HttpResponseRedirect
from movie.models import Movie
from django.core.paginator import Paginator
from django.template import loader


# Create your views here.
def actors(request,actor_slug):
    actor = get_object_or_404(Actor,slug=actor_slug)
    movies = Movie.objects.filter(Actors=actor)

    #pagination
    paginator = Paginator(movies,9)
    page_number = request.GET.get("page")
    movie_data = paginator.get_page(page_number)
    context={
        'movie_data':movie_data , 
        'actor':actor
    }
    template = loader.get_template('actors.html')

    return HttpResponse(template.render(context,request))

templates/actors.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m12">
          <div class="card">
            <div class="card-image">
              <img src="{%static 'img/icons/actor_2.jpg' %}">
              <img id="img-custom-circle-actor" src="{%static 'img/antje.jpg'%}">
              <span style="font-size: 32px;" class="card-title"><b>{{actor}}</b></span>
            </div>
          </div>
        </div>
        <br>
        <h4 class="orange-text">known for:</h4>
        <div class="divider"></div>

        {% for movie in movie_data %}
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              {% if movie.Poster == 'N/A' %}
                <a href="{% url 'movie-details' movie.imdbID%}"><img src="{% static 'img/no_poster.jpg' %}"></a>
              {% else %}
                <a href="{% url 'movie-details' movie.imdbID%}"><img src="{{ movie.Poster.url }}"></a>
              {% endif %}
            </div>
            <div class="card-content">
              <span class="card-title"><b>{{movie.Title}}</b> </span>
              <i class="material-icons left">date_range</i>
              <span class="left">{{movie.Year}}</span>
              <p><b>{{movie.Type}}</b></p>
            </div>
            
          </div>
        </div>
        {% endfor %}
        
        <div class="col s12 m12 center-align">
          {% if movie_data.has_previous %}
          <a href="?page={{movie_data.previous_page_number}}" class="waves-effect waves-light btn">
            <i class="material-icons left">arrow_back</i>Back
          </a>
          {% endif %}

          {% if movie_data.has_next %}
          <a href="?page={{movie_data.next_page_number}}" class="waves-effect waves-light btn">
            <i class="material-icons left">arrow_back</i>Back
          </a>
          {% endif %}
        </div>

      </div>


{% endblock %}
  


  

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Parallax Template - Materialize</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>

  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="https://cdn.jsdelivr.net/gh/amirsaa/easy-Materialize-rtl/materialize-rtl.min.css" rel="stylesheet">

</head>
<body>
  <nav class="light-blue" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="#" class="brand-logo">Logo</a>
      <ul class="left hide-on-med-and-down">
        <li><a href="#">Navbar Link</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  {% block banner %}

  {% endblock %}
 


  <div class="container">
    <div class="section">
      {% block content %}

      
      {% endblock %}

    </div>
  </div>


 

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>

  </body>
</html>

templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<div class="row center-align">
	<form method="post" enctype="multipart/form-data" class="col s12" role="form" action="">
	{% csrf_token %}
	<h3>Edit Profile</h3>
	<div class="row">
		<div class="file-field input-field col s12">
		<div class="btn">
			<span>File</span>
			{{ form.picture }}	
		</div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>	
		</div>
	</div>
	<div class="row">
		<div class="input-field col s6">
		<i class="material-icons prefix">account_circle</i>
			{{ userprofile_form.first_name }}	
		<label for="first_name">First name</label>		
		</div>
	</div>
	<div class="row">
		<div class="input-field col s6">
			<i class="material-icons prefix">account_circle</i>

			{{ userprofile_form.last_name }}	
		<label for="last_name">Last name</label>
		</div>
	</div>
	<div class="row">
		<div class="input-field col s12">
			
			{{ userprofile_form.email }}	
		<label for="email">Email</label>
		</div>
	</div>
	<div class="row">
		<div class="input-field col s12">
			{{ form.location }}	
		<label for="location">Location</label>		
		</div>
	</div>
	<div class="row">
		<div class="input-field col s12">
			{{ form.url }}	
		<label for="url">URL</label>		
		</div>
	</div>
	<div class="row">
		<div class="input-field col s12">
			{{ form.profile_info }}	
		<label for="profile_info">About</label>		
		</div>
	</div>


	{% if form.errors or userprofile_form %}
	<div class="row">
		<div class="col s12">
			<span style="color: red; font-weight: bold;">{{ form.errors }} {{userprofile_form.errors}}</span>
		</div>	
	</div>
	{% endif %}
	<button type="submit" name="action" class="waves-effect waves-light btn"><i class="material-icons left">send</i>Update</button>
	</form>

</div>

{% endblock %}

templates/genre.html
{% extends 'base.html' %}
{% load static %}

{% block banner %}

  
  <div id="index-banner" >
    <div class="section no-pad-bot">
      <div class="container center-align">
        <h1 class="header orange-text">#{{genre}}</h1>

      </div>
    </div>
  </div> 
{% endblock %}

{% block content %}
  
      <!--   Icon Section   -->
      <div class="row">
        {% for movie in movie_data %}
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              {% if movie.Poster == 'N/A' %}
                <a href="{% url 'movie-details' movie.imdbID%}"><img src="{% static 'img/no_poster.jpg' %}"></a>
              {% else %}
                <a href="{% url 'movie-details' movie.imdbID%}"><img src="{{ movie.Poster.url }}"></a>
              {% endif %}
            </div>
            <div class="card-content">
              <span class="card-title"><b>{{movie.Title}}</b> </span>
              <i class="material-icons left">date_range</i>
              <span class="left">{{movie.Year}}</span>
              <p><b>{{movie.Type}}</b></p>
            </div>
            
          </div>
        </div>
        {% endfor %}

        <div class="col s12 m12 center-align">

          {% if movie_data.has_previous %}
          <a href="?page={{movie_data.previous_page_number}}" class="waves-effect waves-light btn">
            <i class="material-icons left">arrow_back</i>Back
          </a>
          {% endif %}

          {% if movie_data.has_next %}
          <a href="?page={{movie_data.next_page_number}}" class="waves-effect waves-light btn">
            <i class="material-icons left">arrow_back</i>Back
          </a>
          {% endif %}

        </div>
      </div>


{% endblock %}
  

  

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block banner %}

  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        
        <div class="row center">
          <h1 class="header center white-text text-lighten-2">Find your favorite movie</h1>
          <div class="row">
            <form class="col s12">
              <div class="row">
                <div class="input-field col s12">
                  <textarea  id="textarea1" type="submit" name='q' value="{{request.GET.q}}" class="materialize-textarea white-text"></textarea>
                  <label for="textarea1">Textarea</label>
                </div>
                <button type="submit" class="waves-effect waves-light btn-large"><i class="material-icons right">search</i>button</button>
              </div>
            </form>
          </div>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="{%static 'img/dark-banner.jpg' %}" class="blur-bg" alt="Unsplashed background img 1"></div>
  </div>

  {% endblock %}

  
      {% block content %}
      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">movie</i></h2>
            <h5 class="center">Find your favorite movies</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">library_add</i></h2>
            <h5 class="center">Create watchlist and more</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">rate_review</i></h2>
            <h5 class="center">Review your favorite movie</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>
      {% endblock %}

    


  

templates/movie-Review.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Parallax Template - Materialize</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>

  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="https://cdn.jsdelivr.net/gh/amirsaa/easy-Materialize-rtl/materialize-rtl.min.css" rel="stylesheet">

</head>
<body>
  <nav class="light-blue" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="#" class="brand-logo">Logo</a>
      <ul class="left hide-on-med-and-down">
        <li><a href="#">Navbar Link</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  
  

  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m12">
          <div class="card horizontal">
            <div class="card-image">
              <img src="img/1.jpg">
            </div>
            <div class="card-stacked">
              <div class="card-content">
                <span class="card-title"><b>Intersteller</b> </span>
                <span>movie</span>
                <br>
                <p>
                  We are a team of college students working on this project like it's
                  our full time job. Any amount would help support and continue development on this project and is greatly appreciated.
                </p>
                <div class="divider"></div>
                <div class="col s12 m12">
                  <div class="card-panel grey lighten-5 z-depth-1">
                    <div class="row valign-wrapper">
                      <div class="col s4 center-align">
                        <img src="img/no_avatar.jpg" alt="" class="circle responsive-img">
                        <span><b> mehdi amz</b></span>
                        <span>@mehdiamz</span>
                      </div>
                      <div class="col s8">
                        <h5>Rated this movie</h5>
                        <h5>10 / 10</h5>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>


      <h4>Reviews</h4>
      <div class="divider"></div>
      <div class="row">
        <div class="col s12 m12">
          <div class="card">
            
            <div class="card-content">
              <span class="card-title"><b>mehdi amz</b><span class="left">Review<i class="material-icons left">rate_review</i></span></span>
              <p>@mehdiamz</p>
              <p><b>20 october 2020</b></p>
              <br>
              <p>We hope you have enjoyed using Materialize and if you feel like it has helped you 
              out and want to support the team you can help us by donating or backing us on Patreon.
              Any amount would help support and continue development on this project and is greatly appreciated.</p>
            </div>
            <div class="card-action">
              <a href="#"><i class="material-icons ">thumb_up</i>100</a>
              <a href="#"><i class="material-icons ">thumb_down</i>100</a>
            </div>
          </div>
        </div>
      </div>
      <h4>Comments</h4>
      <div class="divider"></div>
      <div class="row">
        <div class="col s12 m12">
          <div class="card">
            
            <div class="card-content">
              <ul class="collection">
                <li class="collection-item avatar">
                  <img src="img/no_avatar.jpg" alt="" class="circle">
                  <span class="title"><b>Mehdi amz</b></span>
                  <p>@mehdiamz</p>
                  <p>29 octobr</p>
                  <br>
                    We hope you have enjoyed using Materialize and if you feel like it has helped you 
                    out and want to support the team you can help us by donating or backing us on Patreon.
                    Any amount would help support and continue development on this project and is greatly appreciated.
                  
                  <a href="#!" class="secondary-content"><i class="material-icons red-text">delete_forever</i></a>
                </li>
              </ul>
            </div>
            <div class="card-action">
              <form >
                <div class="row">
                  <div class="input-field col s12">
                    <textarea id="textarea1" class="materialize-textarea white-text"></textarea>
                    <label for="textarea1">Comment</label>
                  </div>
                  <a class="waves-effect waves-light btn"><i class="material-icons right">send</i>Send</a>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>        



    </div>
  </div>


  

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>

  </body>
</html>

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m12">
          <div class="card">
            <div class="card-image">
              <img src="{%static 'img/icons/banner.jpg'%}">
              {% if profile.picture %}
              <img id="img-custom-circle-actor" src="{{profile.picture.url}}">
              {% else %}
              <img id="img-custom-circle-actor" src="{%static 'img/no_avatar.jpg'%}">
              {% endif %}
              <span style="font-size: 32px;" class="card-title"><b>{{profile.first_name}} {{profile.last_name}}</b></span>
            </div>
            <div class="card-content">
              <div class="row">
                <div class="col s12 m4">
                  <ul class="collection with-header">
                    <li class="collection-header"><h5>User information</h5></li>
                    <li class="collection-item">Location: <b>{{profile.location}}</b></li>
                    <li class="collection-item">Link: <a><b>{{profile.url}}</b></a></li>
                    <li class="collection-item">Bio: 
                      {{profile.profile_info}}
                    </li>
                  </ul>
                  <a href="{% url 'authy:edit-profile' %}" class="btn">Edit profile</a>
                </div>
                <div class="col s12 m8">
                  <ul class="collection">
                    <li class="collection-item avatar">
                      <i class="material-icons circle blue">local_movies</i>
                      <span class="title">Movies Watched</span>
                      <p class="center-align"><b>100</b></p>
                      <a href="#!" class="secondary-content"><b>Show list</b></a>
                    </li>
                    <li class="collection-item avatar">
                      <i class="material-icons circle green">movie</i>
                      <span class="title">Series Watched</span>
                      <p class="center-align"><b>100</b></p>
                      <a href="#!" class="secondary-content"><b>Show list</b></a>
                    </li>
                    <li class="collection-item avatar">
                      <i class="material-icons circle red">playlist_play</i>
                      <span class="title">Movies in Watche list</span>
                      <p class="center-align"><b>100</b></p>
                      <a href="#!" class="secondary-content"><b>Show list</b></a>
                    </li>
                    <li class="collection-item avatar">
                      <i class="material-icons circle orange">rate_review</i>
                      <span class="title">Movies Reviewed</span>
                      <p class="center-align"><b>100</b></p>
                      <a href="#!" class="secondary-content"><b>Show list</b></a>
                    </li>
                  </ul>
                </div>

              </div>
            </div>

          </div>
        </div>
        
        <h4 class="orange-text">known for:</h4>
        <div class="divider"></div>
        <div class="row">
          <div class="col s12 m4">
            <div class="card">
              <div class="card-image">
                <img src="img/1.jpg">
              </div>
              <div class="card-content">
                <span class="card-title"><b>Intersteller</b> </span>
                <i class="material-icons left">date_range</i>
                <span class="left">2010</span>
                <p><b>movie</b></p>
              </div>
              
            </div>
          </div>
        </div>
        
        <div class="col s12 m12 center-align">
          <a class="waves-effect waves-light btn"><i class="material-icons left">add</i>Load more</a>
        </div>

      </div>


{% endblock %}


  

 

templates/rate.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Parallax Template - Materialize</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>

  <link href="css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="https://cdn.jsdelivr.net/gh/amirsaa/easy-Materialize-rtl/materialize-rtl.min.css" rel="stylesheet">

</head>
<body>
  <nav class="light-blue" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="#" class="brand-logo">Logo</a>
      <ul class="left hide-on-med-and-down">
        <li><a href="#">Navbar Link</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  
  

  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m12">
          <div class="card horizontal">
            <div class="card-image">
              <img src="img/1.jpg">
            </div>
            <div class="card-stacked">
              <div class="card-content">
                <span class="card-title"><b>Intersteller</b> </span>
                <span>movie</span>
                <br>
                <p>
                  We are a team of college students working on this project like it's
                  our full time job. Any amount would help support and continue development on this project and is greatly appreciated.
                </p>
                <div class="divider"></div>
                <br>
                <div class="input-field col s12">
                  <select>
                    <option value="" disabled selected>Rate</option>
                    <option value="1">Option 1</option>
                    <option value="2">Option 2</option>
                    <option value="3">Option 3</option>
                  </select>
                  <label>Rate this movie</label>
                </div>
                
                  <div class="input-field col s12">
                    <textarea id="textarea1" class="materialize-textarea"></textarea>
                    <label for="textarea1">Textarea</label>
                  </div>
                  
                <a class="waves-effect waves-light btn"><i class="material-icons left">star</i>Rated</a>

              </div>
            </div>
          </div>
        </div>
      </div>


            



    </div>
  </div>


  

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="js/materialize.js"></script>
  <script src="js/init.js"></script>

  </body>
</html>

templates/search-resault.html
{% extends 'base.html' %}
{% load static %}

{% block banner %}  
  <div id="index-banner" >
    <div class="section no-pad-bot">
      <div class="container">
       <h2 class="header orange-text">Search resault for:</h2>
      <h2 >Batman</h2> 

      </div>
    </div>
  </div> 
{% endblock %}
  
      {% block content %}
      <!--   Icon Section   -->
      <div class="row">
        {% for movie in movie_data.Search %}
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              {% if movie.Poster == 'N/A' %}
                <a href="{% url 'movie-details' movie.imdbID%}"><img src="{% static 'img/no_poster.jpg' %}"></a>
              {% else %}
                <a href="{% url 'movie-details' movie.imdbID%}"><img src="{{ movie.Poster }}"></a>
              {% endif %}
            </div>
            <div class="card-content">
              <span class="card-title"><b>{{movie.Title}}</b> </span>
              <i class="material-icons left">date_range</i>
              <span class="left">{{movie.Year}}</span>
              <p><b>{{movie.Type}}</b></p>
            </div>
            
          </div>
        </div>
        {% endfor %}
        <div class="col s12 m12 center-align">
          <a href="{% url 'paginate' query page_number %}" class="waves-effect waves-light btn"><i class="material-icons left">add</i>Load more</a>
        </div>
        
      </div>
      {% endblock %}

   


  

 


 